{% set name = "pyotf" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyotf-{{ version }}.tar.gz
  sha256: 78ca6efcfa575894a93661ebbc5e602dc83d083620d62f925ccbd1c1dc2d7b27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dphtools
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scikit-image
    - scipy
    - tifffile

test:
  imports:
    - pyotf
    - pyotf.microscope
    - pyotf.phaseretrieval
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/david-hoffman/pyOTF
  summary: A python library for simulating and analyzing microscope point spread functions (PSFs)
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goanpeca
